### ISSUE TITLE
Como?

### ISSUE THREAD

**Issue by germanengit** [moiatgit/abs-guide-ca#1]
Hola moiat
¿Cómo organizas tu, proyecto?
¿Qué documentos están listos para traducir?.
¿La salida traducida va ha ser los .rst, o esto es herencia?

¿Cómo obtienes los .rst, utilizas algún tipo de script "formato_entrada"2rst?.
Sería genial tanto para conseguir los documentos de entrada (para sphinx) , como para usar gettext
en el proceso de traducción y poder volver a convertir el documento html (generados a partir de sphinx-intl ..... make -e .... textinfo p.e.  ) a rst.

Perdón por la lluvia de preguntas, mejor decir ¿Cómo puedo colaborar?

P.D.: soy ex alumno del fatídico JuanitoElAustriaco ( el que está aprendiendo a usar sphinx-doc y a volver a escribir ).
Es posible la comunicación mediante el correo de ex-alumnos, así no hay que abrir issues en tu flujo de  trabajo **galonso@ies"tu sabes".org**.
re.P.D.: Espero que estés disfrutando de tus vacaciones.

**Comment by moiatgit** [comment]
Buenas!

Estoy de vacaciones con poca cobertura y sin pc. Te contesto cuando vuelva.

Genial tu interés. Sphinx es realmente impresionante! Gracias por
presentármelo!

Un saludo
El dia 26/07/2015 9:07, "germanengit" <notifications@github.com> va
escriure:

**Comment by moiatgit** [comment]
Hola germanengit ;)

Ahora que pillo un PC, intento ser breve pero contestar "todas" tus
preguntas

El proyecto está organizado de manera orgánica, es decir, a medida que voy
descubriendo casos, adapto la estructura.

Por el momento, hay los siguientes elementos básicos (el resto puedes
ignorarlo con tranquilidad):
1. abs-guide.r10/ contiene la versión original en Inglés (incluye una
   versión en .rst obtenida medio automáticamente con algunas transformaciones
   con vim/sed)
2. sphinx-abs/ contiene:
   - los .rst en trabajo. Los que aparecen con el título precedido por XXX
     es que aun están por finalizar (o empezar a traducir)
   - _scripts/ donde voy dejando todos los guiones que traduzco. Me gusta
     tenerlos fuera de los rst para poderlos provar
   - _build/ esta carpeta no está gestionada por git. Es donde "make html"
     deja el resultado traducido. Sería la salida traducida
   - el resto de carpetas i ficheros corresponden a elementos de sphinx. He
     modificado ligeramente el tema que uso y alguna traducción.

Como colaborar? Bueno, eso ya depende de tu interés. Se me ocurren varias
maneras:

a) haciéndome un fork (veo que ya lo tienes), escogiendo un tema que te
resulte de interés personal para aprender i, preferiblemente de los que
están por traducir (recuerda que el título empieza por XXX i que puedes
verlos ya en index.html)

b) haciendo tu propia versión en castellano. Aun así, creo que la
colaboración puede ser beneficiosa para ambos pues, las dos lenguas
(Cas+Cat) son muy próximas y,  al menos por mi parte, a menudo me encuentro
con dificultades para decidir como traducir algún elemento concreto. Por no
hablar de lo guapo que podría quedar un sitio donde poder consultar la guía
en diferentes idiomas!

c) mejorando el uso de sphinx (css, layouts, etc)

d) convirtiendo la versión original en Inglés a sphinx. Hay muchos
elementos que no se traducen automáticamente.

Bueno, espero haberte dado suficientes ideas. Ahora a ver si te animas y
encuentras tu ratillo. Ya me comentarás

Un saludo

P.D. creo que aprovecharé parte de este mensaje para documentar el proyecto
de traducción, por si alguien más se animase!

**Comment by germanengit** [comment]
Hola moiatgit ;)

# Mi visión inicial

Sobre toda tu organización me parece perfecta, yo me adaptaré. Mi interés es para poder proporcionarte el feedback en catalán, entiendo que son los rst traducidos. 
Sobre la versión castellana, sería la traducción del catalán en principio. (Así aprendo, de tus partes traducidas pillo tu estilo y vocabulario).
Esto es debido a que te considero el revisor de la traducción catalana (evidentemente), y aúnque sea indireta e involuntariamente de la castellana (mi inglés es pobre, y el libro tiene tela).

Tengo en mente varias cuestiones que me bloquean e incentivan. Si el documento traducido final es el rst, al traducir y mandar el _pull request_, en el supuesto de que hubiese una frase que está mal o no se ajusta a tu visión lingüística, estilo, simple error sintáctico, .... o directamente incorrecta . :
- Puedes rechazarlo todo por una frase !
- Aceptarlo y tener que corregirlo rompiendo tu flujo de trabajo o planes. Este punto me mosquea.

Debido a estos pensaientos voy a hacer una rama para investigar gettext.

Mi rama master será siempre tu clon, yo trabajaré en mis ramas propias donde tendré la versión castellana (invitación a toda america latina).
Si aparecieran traductores al español, yo  reenviaría traducciones derivadas, según tus filtros estilísticos al catalán.
(Consideraré las dos versiones distintas como obras derivadas en principio)

# Sobre sphinx

Yo utilizo la versión 1.1.3 de sphinx, instalada de los repos de Debian Wheezy.

## Mi interés actual sobre sphinx

Veo un punto flojo en sphinx y su visión del soporte para traducción, que quizás esté más enfocado a la internacionalización del software y a la traducción de un proyecto cerrado (simplemente traducir no ampliar).

Me explico: nuestro marco de trabajo es una entrada rst con la que puedes hacer virguerías (generalmente la picas tú, documentando tu proyecto). Pero al traducir, utilizando sphinx-intl, tomo una entrada rst  y no tengo una salida rst, a no ser que traduzca directamente estos rst. Mientras que si tengo salidas html por varias vías. 
¿Cómo haría, si yo quiero ampliar una traducción (Derivar la obra)?. Debo parsear html-default con todos sus <div> o html-textinfo a rst otra vez o pasarme a dockbook (Esto último es humor negro je.je). Así que yo adopto otra rama gettex-way donde utilizaré sphinx-intl, para investigar y aprender sobre el tema.
En todo caso, desde la salida text puedo construir un rst con las directivas sphinx, aúnque sea copy-paste y proponerte una traducción. No PROBLEMO !

# Documentación del proyecto

Una de las cosas que más me ayudaría para arrancar es una guía de vocabulario, sin tener en cuenta cuestiones gramaticales de momento. 
De hecho traducí una página, con lo que después ví que no era tu vocabulario.
Por ejemplo:
comand-line ->línia de comandes, yo utilicé línia d'ordres
shell -->shell ; preferido a "interpret de comandes"
etc ...
Quizás la sección wiki puede tener algo al respecto. O cualquier otro docu

P.D No olvides que estás de vaciones

**Comment by germanengit** [comment]
Cambios en la rama, en breve

**Comment by moiatgit** [comment]
​Algun comentario:
1. he creado el fichero glossari.rst​ en el que voy incluyendo las
   diferentes decisiones de traducción. Por supuesto no está ni completo ni es
   inamovible.
2. diría que si tu objetivo es hacer la versión en castellano, simplemente
   puedes crear una nueva carpeta en la raiz del proyecto llamada abs-es o
   similar, e ir añadiendo tus traducciones. Eso simplificaría los merge. En
   caso que hagas alguna propuesta sobre mis .rst (en catalán) yo vería el
   cambio en los diff y no debería de suponerme ningún trauma.
3. me he apuntado en transifex https://www.transifex.com/, que contiene
   el proyecto de traducción de la documentación de sphinx para intentar
   entender el flujo de trabajo que proponen los de Sphinx para traducir. Me
   parece que es un poco engorroso (en una primera visión) pues te obliga a
   usar su editor on-line (no-sin-mi-vim!) pero tiene un control muy
   interesante para la traducción colaborativa (incluye control de párrafos,
   revisiones, etc) Ya había visto cosas similares (he traducido algunas
   frases en diversas aplicaciones web) y de momento no quisiera meterme en
   ello (repito lo de no-sin-mi-vim)
   Respecto a las demás opciones de traducción que proponen, incluyendo
   sphinx-intl, reconozco que las he mirado demasiado en diagonal como para
   tener una idea clara de como funcionan.
4. Sí, estoy de vacaciones (igual que tu ;) ) y a partir de mañana mi
   acceso a internet se reducirá drásticamente (a cero!) durante unos cuantos
   días!

Seguimos

**Comment by germanengit** [comment]
Ok.
Quzás veas algunas burradas en los commits. Estoy aprendiendo a usar git, también voy a hacer
un parón para leer mejor pro-git. Y estoy pensado en ver como documentan los de Mongodb
que utilizan sphinx y empiezo un curso suyo la semana que viene.

PD.  Que disfrutes de tus días offline.
